<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="STM32_Timer.cs" />
    <Reference Include="Infrastructure"><HintPath>../renode-bin/Infrastructure.dll</HintPath></Reference>
  </ItemGroup>
</Project>
